vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        team_file:
            uri_prefix: /uploads/images/teamAvatar
            upload_destination: '%upload_team_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        creche_file:
            uri_prefix: /uploads/images/crechePictures
            upload_destination: '%upload_creche_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
